### ISSUE TITLE
Proposal: Branch based collaboration

### ISSUE THREAD

**Issue by C0DECYCLE** [Perytron/UZH#25]
_This issue should serve as a place to discuss the following proposal._

**IS:** Collaboration is carried out by forking the entire repo, committing own solutions, open PR, merge.
**PROPOSAL:** Inside the main repo create new branch (e.g. "9.1 -user- solution"), committing own solution, open PR, merge, delete branch.

**PROS:**
- Only the main instance of the repo exists. (No duplicates)
- No syncing with the main repo.
- Clearer version history.
- Approach used in the professional software industry.

**CONS:**
- Migration work.
- Branch management.

**MIGRATION PROPOSAL:** 
- Inform past collaborators.
- Choose migration date.
- Protect main branch to only allow edit by owner. (@Perytron)
- Setup branch rules.
- Adjust readme.
- Invite past collaborators.

_PS: In case of this proposal, if someone new would want to collaborate, the person must first contact the owner to be added as a collaborator. (e.g. via an issue)_

**Comment by C0DECYCLE** [comment]
@Perytron @Patertuck

**Comment by Perytron** [comment]
Wow, Noah, thank so much for this proposal 😍. In contrast to you, I know nothing about the industry yet and have always done things very rudimentary because I have not learned it yet.
I am very much in favor of this change, especially because it is a step towards a more professional approach.

However, could you elaborate further on branches? The most I have dealt with branches is creating a 'dev' branch and merging it with 'main' when I've finished implementing a new feature (you know, I fix issues in production 🤣). So what would the workload of other participants be? They would themselves create a new branch, change it however they like, then create a pull request and I would merge their branch with the 'main' branch to publish the changes?

I honestly don't know why people keep quitting sharing their solutions. They never tell me why, I hope it was not because of the way I administer this repository.

**Comment by Perytron** [comment]
This would mean that I would add you both as collaborators but restricting access to the main/master branch. I would also need to create a seperate branch dedicated to one-time contributors that still go the forked way, right? Because when protecting the main branch, I would hinder these people in creating a PR for the main branch, right?

**Comment by Perytron** [comment]
Guys, look what we have achieved yesterday! 90 unique visitors! 😍 It is really worth it to spend some time perfecting this repository.
<img src="https://user-images.githubusercontent.com/59439327/204542845-f1dd524f-b77d-4145-904c-2a9a0e36e058.png" width="200" />

**Comment by C0DECYCLE** [comment]
> Guys, look what we have achieved yesterday! 90 unique visitors! 😍 It is really worth it to spend some time perfecting this repository. <img alt="" width="200" src="https://user-images.githubusercontent.com/59439327/204542845-f1dd524f-b77d-4145-904c-2a9a0e36e058.png">

Meaning almost 25% of all students taking the Info1 course visited yesterday! Really amazing!

**Comment by C0DECYCLE** [comment]
Regarding branches, the use case would be very similar to your experience with the dev branch and the described workflow.

In the industry/software company I work besides studying, the workflow is the following:
- The team plans a milestone with features for the software and a due date for the milestone.
- The lead creates specific issues for the features and assigned them to team members.
- The team members create a feature branch linked to the issue and implements the feature/bugfix.
- When they’re done they open a PR and request a review from a authorised reviewer like a senior dev.
- When the reviewer approves it it gets merged into the main branch.
- This continues until the milestone is reached and the cycle continues from the beginning with the planning of a new one.

But of course in the case of the repo it has to be different so my proposal would be:
- If someone wants to contribute, the person requests contribution and gets added to the collaborators on the GitHub settings. That is necessary because in order to create a new branch it is required by GitHub to be an official collaborator. (See [docs](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/permission-levels-for-a-personal-account-repository#collaborator-access-for-a-repository-owned-by-a-personal-account))
- Then their able to create a new branch for example called: “9.1-username-solution”.
- After that the can locally checkout to that new branch and commit their solution.
- When their finish, the can open a PR to merge their feature branch into the main branch as well as linking @Perytron as reviewer. 
- Then if everything checks out @Perytron merges it into the main and the branch can be deleted.

Additional points:
- If later someone has to correct their solution, they can reopen the branch, commit again and request a PR again in the same way.
- It’s very important to protect the main branch with rules so that no-one can harm the main branch which is the main entry point for the visiting students. Protecting the main branch would mean that no one can directly edit it, every edit would go through branches and PR’s of those branches with one approval of a authorised person.
- For one time contributors the current variant could stay in place.
- Additional protecting rules to all branches are a good idea to keep everything in order and prevent chaos.


About the quitting, I also saw the pattern when I went through the history. I’m certain it’s not because of the excellent administration on your part. 
I theorise: maybe it could be that they don’t reach enough points on access that they’re confident enough to share.

**Comment by C0DECYCLE** [comment]
Regarding branches, the use case would be very similar to your experience with the dev branch and the described workflow.

In the industry/software company I work besides studying, the workflow is the following:
- The team plans a milestone with features for the software and a due date for the milestone.
- The lead creates specific issues for the features and assigned them to team members.
- The team members create a feature branch linked to the issue and implements the feature/bugfix.
- When they’re done they open a PR and request a review from a authorised reviewer like a senior dev.
- When the reviewer approves it it gets merged into the main branch.
- This continues until the milestone is reached and the cycle continues from the beginning with the planning of a new one.

But of course in the case of the repo it has to be different so my proposal would be:
- If someone wants to contribute, the person requests contribution and gets added to the collaborators on the GitHub settings. That is necessary because in order to create a new branch it is required by GitHub to be an official collaborator. (See [docs](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/permission-levels-for-a-personal-account-repository#collaborator-access-for-a-repository-owned-by-a-personal-account))
- Then their able to create a new branch for example called: “9.1-username-solution”.
- After that the can locally checkout to that new branch and commit their solution.
- When their finish, the can open a PR to merge their feature branch into the main branch as well as linking @Perytron as reviewer. 
- Then if everything checks out @Perytron merges it into the main and the branch can be deleted.

Additional points:
- If later someone has to correct their solution, they can reopen the branch, commit again and request a PR again in the same way.
- It’s very important to protect the main branch with rules so that no-one can harm the main branch which is the main entry point for the visiting students. Protecting the main branch would mean that no one can directly edit it, every edit would go through branches and PR’s of those branches with one approval of a authorised person.
- For one time contributors the current variant could stay in place.
- Additional protecting rules to all branches are a good idea to keep everything in order and prevent chaos.


About the quitting, I also saw the pattern when I went through the history. I’m certain it’s not because of the excellent administration on your part. 
I theorise: maybe it could be that they don’t reach enough points on access that they’re confident enough to share.

**Comment by dreamfarer** [comment]
@C0DECYCLE Hey Noah, do you want to join me and @Patertuck on Discord? We are currently discussing how to implement your proposal 😄.

**Comment by C0DECYCLE** [comment]
Sure one sec

> @C0DECYCLE Hey Noah, do you want to join me and @Patertuck on Discord? We are currently discussing how to implement your proposal 😄. My Discord tag would be `Perytron#0001`

**Comment by C0DECYCLE** [comment]
Log: Proposal accepted.
