### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by Patertuck** [Perytron/UZH#28]
To-Do List:

- [x] Add cloning step
- [x] Support other method, Git CLI 
- [x] Support other method, PyCharm 
- [x] Support other method, VSCode
- [x] Clarifying cloning: No need to re-clone it everytime
- [x] Clarify what happens with the branches after the PR
- [x] Describe the action of restoring a deleted pr if adjustments have be made.
- [x] Reminder to please write, commit messages etc. in present. (Add instead of Added)
- [x] Add switching back to main after creating pull request. (I had problems switching back to main from a deleted branch)
- [x] Add `git fetch --prune` to delete local copies of remote branches that have been deleted
- [x] Add `git stash` `git switch BRANCH_NAME` `git stash apply`: Used to carry over changes made to **main** when you forgot switching the branch to your newly created feature branch. Nope, that did not happen to me ever 🤣.
- [x] Add Disclaimer for the usage of the repository (e.x. only use for assistance, not just copy paste)
- [x] Prettify readme with icons?

**Comment by Perytron** [comment]
Hey @C0DECYCLE @Patertuck 😊

I've created a [new branch](https://github.com/Perytron/UZH/tree/28-update-readme) where the update of the Readme happens. I've already created a guide on how to perform the new workflow - from creating a new branch to issuing a pull request.

**Comment by Perytron** [comment]
It is 02:30 am and I am so tired lmao... Need to get up at 07:15 am. Wish me luck. It was totally worth it. ❤️

**Comment by C0DECYCLE** [comment]
Really cool, thank you!

**Comment by C0DECYCLE** [comment]
Will do the support for pycharm

**Comment by Perytron** [comment]
I always have a hard time choosing the layout of the Readme in order to be easily readable. It looks so cluttered in my opinion. If you guys have a better idea, feel free to propose any changes! 😍

**Comment by Patertuck** [comment]
@Perytron I think it's well designed and easy to find the information you need.

**Comment by C0DECYCLE** [comment]
pushed suggestion for little layout changes

**Comment by Perytron** [comment]
> pushed suggestion for little layout changes

Very much in favor, looks great! 🥇
