### ISSUE TITLE
Repo improvements

### ISSUE THREAD

**Issue by C0DECYCLE** [Perytron/UZH#33]
_Under "Insights" > "Community Standards" there's a checklist with improvements._

**IS:** Currently missing 
- [Code of conduct](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project)
- [Contributing](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)
- [Security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository)
- [Issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
- [Pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

**SHOULD:** Implement missing points

**Comment by Perytron** [comment]
Please use [this branch](https://github.com/Perytron/UZH/tree/33-repo-improvements) dedicated to this issue when implementing missing files.

**Comment by Perytron** [comment]
We need to decide on how the code structure of an exercise should look like. @Patertuck and I propose the following structure:
```
004 Functions/
├─ Task 1 Factorial/
│  ├─ Perytron/
│  │  ├─ script.py
│  ├─ C0DECYCLE/
│  │  ├─ .../
│  ├─ Patertuck/
│  │  ├─ .../
│  ├─ .../
│  ├─ tests.py
│  ├─ Template/
│  │  ├─ Public/
│  │  │  ├─ script.py
│  │  │  ├─ tests.py
│  │  ├─ description.md
```
The key thing here is that there is one **tests.py** per task where everyone adds their tests. Furthermore, there is a template folder where everything from Access gets dumped into. In the end, the solution folder of every individual only contains the scripts that have been changed for the grading.
You can use [ASCII Tree Generator](https://ascii-tree-generator.com/) to propose a new structure.

What do you @C0DECYCLE or others think about it?

**Comment by C0DECYCLE** [comment]
LGTM! If no one opposes this proposal, it shall be implemented. 
The question is, under this issue/branch or should we make a separate? and who wants to be assigned to that task?

**Comment by Perytron** [comment]
@C0DECYCLE I've posted it here because I want to include it into the "Contributing" guidelines. After we have decided, I will open up another issue with a different branch to actually execute it. Unless someone is very keen on performing this task, I will work through it the coming weekend.

**Comment by Patertuck** [comment]
Sounds good to me. @Dreamfarer will you go through the old Exercises too  and change the format or do we just start at 10 and do it for the future?

**Comment by Perytron** [comment]
@Patertuck I'll go through the old excercises too. However, we need to figure out on how to properly communicate this matter to future collaborators so that I don't have to adjust the structure of every PR 🤣.

**Comment by C0DECYCLE** [comment]
I would also highly recommend that we keep it consistent retroactively.

**Comment by C0DECYCLE** [comment]
> @Patertuck I'll go through the old excercises too. However, we need to figure out on how to properly communicate this matter to future collaborators so that I don't have to adjust the structure of every PR 🤣.

agree

**Comment by C0DECYCLE** [comment]
> @C0DECYCLE I've posted it here because I want to include it into the "Contributing" guidelines. After we have decided, I will open up another issue with a different branch to actually execute it. Unless someone is very keen on performing this task, I will work through it the coming weekend.

We could also do 50/50, one ports 0-5 the other 6-10?

**Comment by Perytron** [comment]
> @Patertuck I'll go through the old excercises too. However, we need to figure out on how to properly communicate this matter to future collaborators so that I don't have to adjust the structure of every PR 🤣.

I mean, I could just reject the request and point them towards the guidelines but leave the PR open. Every further commit will automatically be added to the PR anyway, I guess. I think if we implement the "Contribution" file, GitHub will make them acknowledge it before their first issue/PR. I therefore hope it won't be as big of a problem.

**Comment by Perytron** [comment]
> > @C0DECYCLE I've posted it here because I want to include it into the "Contributing" guidelines. After we have decided, I will open up another issue with a different branch to actually execute it. Unless someone is very keen on performing this task, I will work through it the coming weekend.
> 
> We could also do 50/50, one ports 0-5 the other 6-10?

Sure, if you have time it would be very helpful indeed! 🥰You can choose which one you would like to do.

**Comment by C0DECYCLE** [comment]
> > @Patertuck I'll go through the old excercises too. However, we need to figure out on how to properly communicate this matter to future collaborators so that I don't have to adjust the structure of every PR 🤣.
> 
> 
> 
> I mean, I could just reject the request and point them towards the guidelines but leave the PR open. Every further commit will automatically be added to the PR anyway, I guess. I think if we implement the "Contribution" file, GitHub will make them acknowledge it before their first issue/PR. I therefore hope it won't be as big of a problem.


You right, generally nothing should be merged to master/main unless its waterproof.

**Comment by C0DECYCLE** [comment]
> > > @C0DECYCLE I've posted it here because I want to include it into the "Contributing" guidelines. After we have decided, I will open up another issue with a different branch to actually execute it. Unless someone is very keen on performing this task, I will work through it the coming weekend.
> > 
> > 
> > We could also do 50/50, one ports 0-5 the other 6-10?
> 
> Sure, if you have time it would be very helpful indeed! 🥰You can choose which one you would like to do.

0-5

**Comment by C0DECYCLE** [comment]
> 

In this fashion, sorry for breaking main yesterday 😂

**Comment by Perytron** [comment]
> > You right, generally nothing should be merged to master/main unless its waterproof.
> 
> In this fashion, sorry for breaking main yesterday 😂

You know what's funny tho, you did not actually break it, haha. I mean, it was me who pushed it into main 🤣

**Comment by C0DECYCLE** [comment]
> > > You right, generally nothing should be merged to master/main unless its waterproof.
> > 
> > 
> > In this fashion, sorry for breaking main yesterday 😂
> 
> You know what's funny tho, you did not actually break it, haha. I mean, it was me who pushed it into main 🤣

git blame 👀

**Comment by C0DECYCLE** [comment]
> We need to decide on how the code structure of an exercise should look like. @Patertuck and I propose the following structure:
> 
> ```
> 004 Functions/
> ├─ Task 1 Factorial/
> │  ├─ Perytron Solution/
> │  │  ├─ script.py
> │  ├─ C0DECYCLE Solution/
> │  │  ├─ .../
> │  ├─ Patertuck Solution/
> │  │  ├─ .../
> │  ├─ .../
> │  ├─ tests.py
> │  ├─ Template/
> │  │  ├─ Public/
> │  │  │  ├─ script.py
> │  │  │  ├─ tests.py
> │  │  ├─ description.md
> ```
> 
> The key thing here is that there is one **tests.py** per task where everyone adds their tests. Furthermore, there is a template folder where everything from Access gets dumped into. In the end, the solution folder of every individual only contains the scripts that have been changed for the grading. You can use [ASCII Tree Generator](https://ascii-tree-generator.com/) to propose a new structure.
> 
> What do you @C0DECYCLE or others think about it?

About the file structure, how should we proceed in 000?

**Comment by Perytron** [comment]
> > We need to decide on how the code structure of an exercise should look like. @Patertuck and I propose the following structure:
> > 
> > ```
> > 004 Functions/
> > ├─ Task 1 Factorial/
> > │  ├─ Perytron Solution/
> > │  │  ├─ script.py
> > │  ├─ C0DECYCLE Solution/
> > │  │  ├─ .../
> > │  ├─ Patertuck Solution/
> > │  │  ├─ .../
> > │  ├─ .../
> > │  ├─ tests.py
> > │  ├─ Template/
> > │  │  ├─ Public/
> > │  │  │  ├─ script.py
> > │  │  │  ├─ tests.py
> > │  │  ├─ description.md
> > ```
> > 
> > The key thing here is that there is one **tests.py** per task where everyone adds their tests. Furthermore, there is a template folder where everything from Access gets dumped into. In the end, the solution folder of every individual only contains the scripts that have been changed for the grading. You can use [ASCII Tree Generator](https://ascii-tree-generator.com/) to propose a new structure.
> > 
> > What do you @C0DECYCLE or others think about it?
> 
> About the file structure, how should we proceed in 000?

There is only one file and most likely we won't be adding more as the course is basically over. For Info II, we will be creating another root folder anyways, so, I think it does not really matter. Do as you wish: I thought, either the date of the lecture or the title of the PowerPoint so it is easily recognizable.
