### ISSUE TITLE
Request to get collaborator role

### ISSUE THREAD

**Issue by yuirike** [Perytron/UZH#63]
Hello

Could I get collaborator rights? I'm Rosan. I'll prove my identity by uploading a screenshot of my Uni-Portal page, as I don't really like to look at my face on the UZH-card, I hope that's okay.
*I don't need to state my surname since I'm apparently the only one in this university with that first name.

![Capture](https://user-images.githubusercontent.com/116112098/207555189-043b3df1-e543-4f47-a50e-4ac0d9874e16.PNG)

**Comment by Perytron** [comment]
All good! Thank you Rosan! 👍🏽 I'll give you the collaborator role now, you need to confirm it via e-mail afterwards. Read through the documentation carefully, especially regarding the branch and directory naming conventions. Just contact us if there are any questions left! Thank you! ❤️
