### ISSUE TITLE
Collaborator rights 

### ISSUE THREAD

**Issue by jazzyywazzyy** [Perytron/UZH#82]
Hi guys 

Da isch jazz asking for collaborator rights :) 

Thaaanks

**Comment by C0DECYCLE** [comment]
Nice, Welcome! @Dreamfarer will add you as a collaborator.

**Comment by dreamfarer** [comment]
Hey Jazz! 👋🏽🔥  I'll add you as a collaborator, however, you'll need to confirm it via e-mail afterward. Please read through our documentation carefully, especially regarding the branch and directory naming conventions. It just helps to prevent issues in the future. Thank you! ❤️
