### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by Twhining** [Perytron/UZH#94]
It would be an honor to contribute alongside you. Please accept me into your circle. I assure you I will not disappoint.

greetings Twhining

**Comment by Patertuck** [comment]
Absolutely you can, I believe in you! Hit us up on Whatsapp (just to the one that sent the Github-Link). :)

**Comment by Twhining** [comment]
I would love to contribute, but since i got the contribution rights i didn't do a good solution and GitHub is kinda intimidating to be honest. I'll do my best do get comfortable with it and upload my next solution.
lg Leon

**Comment by Perytron** [comment]
Oh, hey Leon! 🔥 We did not assign you any rights yet, I'll do it right now. You can just contact me on Whatsapp if you need any help! 🌟 We can also show it to you in-between lectures if you want. Be sure to read our documentation at least once, so you know what's up. 😁

**Comment by Twhining** [comment]
Thank you! I'll got thorugh it step by step and we'll see if i'm up for the task. Thanks for the help in advance. 
greetings
